// Automatically generated by astro-icon
// 2da03586406affc3e023f5ad6f10ecfa3abcc2bb92578c990b1351111c78143c

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "telegram"
		| "twitter-alt";
}