// Automatically generated by astro-icon
// bfb78732d5b84e2b714a328592cab4318134c57ee9e0b0cf0c947326ebd36995

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "discord"
		| "telegram"
		| "twitter-alt";
}